getwd()
setwd("E:/SMA/R-data")
a=read.csv("income.csv",header = TRUE)
View(a)
k=head(a)
view(a)
m=data.frame(a$Y2002,a$Y2003)
plot.default(m)
s=write.table(a,file="mydata.csv")
l=jpeg("j.jpeg")
